If URL parsing fails then always fail to match URLs.
w3c/webpayments-method-identifiers pull request #31
Opened 2017-04-20 14:29 UTC by adrianba

Fixes #27.
Fixes #8.

2017-04-20 14:48 UTC, adrianhopebailie approved these changes

2017-04-27 03:46 UTC, marcoscaceres requested changes
This doesn't address the problems that @annevk outlined. We need an actual algorithm that performs the validation and throws a TypeError on validation failure. 

I'll draft an alternative.

2017-04-27 03:46 UTC, marcoscaceres commented on index.html
> +          <li>If the <a>URL parser</a> throws or if either <em>urlA.query</em>
Note that `.query` makes it look like there is an attribute "query" for the URL object - but there is not. We should link to the appropriate concept here. Otherwise, if you want to use the attributes, then this needs to change to ".search" (and check for "not the empty string"). 

I'd prefer we link to the concepts.

2017-04-27 03:46 UTC, marcoscaceres commented on index.html
> +          algorithm with a result of <em>no match</em> and discard <em>A</em>
Can we just return false instead of "no match"?

2017-04-27 04:59 UTC, annevk commented
(Please only mention me if you need me.)

2017-04-27 06:12 UTC, marcoscaceres commented
@adrianba see https://github.com/w3c/webpayments-method-identifiers/pull/35

2017-06-20 05:12 UTC, zcorpan commented on index.html
> +          <li>If the <a>URL parser</a> throws or if either <em>urlA.query</em>
The URL parser doesn't throw, it returns failure.

2017-06-20 05:23 UTC, marcoscaceres commented
This is obsoleted by https://github.com/w3c/webpayments-method-identifiers/pull/35

2017-06-20 05:23 UTC, closed without merging