make fetching URL-PMI optional (closes #33)
w3c/webpayments-method-identifiers pull request #40
Opened 2017-07-24 04:23 UTC by marcoscaceres

2017-07-24 13:27 UTC, ianbjacobs commented
Hi @marcoscaceres,

I am thinking we may want to be more explicit in cautionary statements to payment method owners. Here is the sort of flow I have in mind:

For user agents:
 * It is optional for user agents to fetch PMIs. (I think in your proposal you can drop " As <a>URL-based payment method identifiers</a> serve primarily as identifiers (and not a linked resource), ")

Note to payment method owners:
 * The Working Group is developing a payment method manifest specification that will give
    payment method owners greater control over the ecosystem of payment apps that implement
    their payment method.
* In the absence of a manifest or of broadly deployed implementations of one or more manifest specifications, there is no mechanism to limit which payment apps are able to claim to support a payment method.

[Hit "go" too soon before]

2017-07-26 13:26 UTC, adrianhopebailie requested changes

2017-07-26 13:26 UTC, adrianhopebailie commented on index.html
> +          experiment with Payment Manifest by placing one at the <a>URL-based
This is incorrect. The manifest should be placed at a location that is accessed using the algorithm described at https://w3c.github.io/payment-method-manifest/#accessing

2017-07-28 01:01 UTC, marcoscaceres commented on index.html
> +          experiment with Payment Manifest by placing one at the <a>URL-based
Good catch, will add a reference to that.

2017-08-14 05:52 UTC, marcoscaceres commented on index.html
> +          experiment with Payment Manifest by placing one at the <a>URL-based
I've decided to remove the note entirely. I don't feel comfortable referencing a spec that is not even a FPWD.

2017-08-14 05:54 UTC, marcoscaceres commented
@ianbjacobs and @adrianhopebailie addressed your feedback. Please review.

2017-08-14 08:21 UTC, adrianhopebailie approved these changes

2017-08-14 08:22 UTC, adrianhopebailie commented
My concern was an incorrect statement about the location of a manifest in relation to the URL-based PMI. That has been removed so no further comments from me.

2017-08-14 12:14 UTC, ianbjacobs reviewed
I'm ok with this change.

Marcos, please update the reference elsewhere in the spec from:
 https://w3c.github.io/webpayments/proposals/method-practice/

to:
 https://github.com/w3c/payment-request-info/wiki/PaymentMethodPractice

The WG supported moving the material to that repo.

Thank you,

Ian

2017-08-15 07:32 UTC, merged